# Generated by Django 5.1.3 on 2024-11-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=7)),
                ('mob', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.profile')),
                ('user', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('c_password', models.CharField(max_length=15)),
            ],
            bases=('app1.profile',),
        ),
    ]
