# Generated by Django 5.1.3 on 2024-11-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('mob', models.CharField(max_length=10)),
                ('clas', models.CharField(max_length=10)),
            ],
        ),
    ]
